name: Linter

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  JAVASCRIPT_ES_CONFIG_FILE: .eslintrc

jobs:
  super-linter:
    name: Super Linter
    uses: wabarc/.github/.github/workflows/reusable-super-linter.yml@main

  misspell:
    name: Misspell
    uses: wabarc/.github/.github/workflows/reusable-misspell.yml@main

  alex:
    name: Alex
    uses: wabarc/.github/.github/workflows/reusable-alex.yml@main

  urlcheck:
    name: URLCheck
    uses: wabarc/.github/.github/workflows/reusable-urlcheck.yml@main
