name: Lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
    types: [ opened, synchronize, reopened ]

permissions: write-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code base
        if: github.event_name == 'push'
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Check out code base
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: 'main'
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSON: false
          VALIDATE_ANSIBLE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
