name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  setup:
    name: Initial env
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node 12.x
      uses: actions/setup-node@v2.1.3
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'

  pre-check:
    name: Checkout, install, test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    needs: setup
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - run: yarn install
    - run: yarn run test

  release:
    name: Create and upload release
    runs-on: ubuntu-latest
    needs: pre-check
    steps:
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body:
        draft: false
        prerelease: true

